name: flutter_badged
description: Badge for showing with icon. You can use it in the bottom menu, navigation drawer or in any place you want.
version: 2.0.3
homepage: https://github.com/mishatron/FlutterBadge

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter